// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sport;

#nullable disable

namespace sport.Migrations
{
    [DbContext(typeof(SportingGoodsStoreContext))]
    [Migration("20260319060352_AddPhotoUrlToSportingGoods")]
    partial class AddPhotoUrlToSportingGoods
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sport.AddressesOfPickUpPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"фddresses_of_pick-up_points_id_seq\"'::regclass)");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("фddresses_of_pick-up_points_pkey");

                    b.ToTable("addresses_of_pick-up_points", (string)null);
                });

            modelBuilder.Entity("sport.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category1")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("sport.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.HasKey("Id")
                        .HasName("manufacturers_pkey");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("sport.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<int?>("IdDeliveryPointAddress")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_point_address");

                    b.Property<int>("IdStatus")
                        .HasColumnType("integer")
                        .HasColumnName("id_status");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex("IdDeliveryPointAddress");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdUser");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("sport.Models.OrdersSportingGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer")
                        .HasColumnName("id_order");

                    b.Property<int>("IdSportingGoods")
                        .HasColumnType("integer")
                        .HasColumnName("id_sporting_goods");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id", "IdOrder", "IdSportingGoods")
                        .HasName("orders_sporting_goods_pkey");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdSportingGoods");

                    b.ToTable("orders_sporting_goods", (string)null);
                });

            modelBuilder.Entity("sport.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role1")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("sport.Models.SportingGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Discount")
                        .HasColumnType("integer")
                        .HasColumnName("discount");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int>("IdManufacturer")
                        .HasColumnType("integer")
                        .HasColumnName("id_manufacturer");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("integer")
                        .HasColumnName("id_supplier");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("integer")
                        .HasColumnName("id_unit_of_measurement");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int?>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.HasKey("Id")
                        .HasName("sporting_goods_pkey");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdManufacturer");

                    b.HasIndex("IdSupplier");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.ToTable("sporting_goods", (string)null);
                });

            modelBuilder.Entity("sport.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status1")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("statuses_pkey");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("sport.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Supplier1")
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.HasKey("Id")
                        .HasName("suppliers_pkey");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("sport.Models.UnitsOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UnitOfMeasurement")
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measurement");

                    b.HasKey("Id")
                        .HasName("units_of_measurement_pkey");

                    b.ToTable("units_of_measurement", (string)null);
                });

            modelBuilder.Entity("sport.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("IdRole");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("sport.Models.Order", b =>
                {
                    b.HasOne("sport.AddressesOfPickUpPoint", "AddressesOfPickUpPoint")
                        .WithMany("Orders")
                        .HasForeignKey("IdDeliveryPointAddress")
                        .HasConstraintName("fk_orders_addresses_of_pick-up_points");

                    b.HasOne("sport.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("IdStatus")
                        .IsRequired()
                        .HasConstraintName("fk_orders_statuses");

                    b.HasOne("sport.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("fk_orders_users");

                    b.Navigation("AddressesOfPickUpPoint");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport.Models.OrdersSportingGood", b =>
                {
                    b.HasOne("sport.Models.Order", "IdOrderNavigation")
                        .WithMany("OrdersSportingGoods")
                        .HasForeignKey("IdOrder")
                        .IsRequired()
                        .HasConstraintName("fk_orders_sporting_goods_orders");

                    b.HasOne("sport.Models.SportingGood", "IdSportingGoodsNavigation")
                        .WithMany("OrdersSportingGoods")
                        .HasForeignKey("IdSportingGoods")
                        .IsRequired()
                        .HasConstraintName("fk_orders_sporting_goods_sporting_goods");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdSportingGoodsNavigation");
                });

            modelBuilder.Entity("sport.Models.SportingGood", b =>
                {
                    b.HasOne("sport.Category", "Category")
                        .WithMany("SportingGoods")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("fk_sporting_goods_categories");

                    b.HasOne("sport.Models.Manufacturer", "Manufacturer")
                        .WithMany("SportingGoods")
                        .HasForeignKey("IdManufacturer")
                        .IsRequired()
                        .HasConstraintName("fk_sporting_goods_manufacturers");

                    b.HasOne("sport.Models.Supplier", "Supplier")
                        .WithMany("SportingGoods")
                        .HasForeignKey("IdSupplier")
                        .IsRequired()
                        .HasConstraintName("fk_sporting_goods_suppliers");

                    b.HasOne("sport.Models.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("SportingGoods")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .HasConstraintName("fk_sporting_goods_units of measurement");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");

                    b.Navigation("Supplier");

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("sport.Models.User", b =>
                {
                    b.HasOne("sport.Models.Role", "IdRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("fk_ussers_roles");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("sport.AddressesOfPickUpPoint", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("sport.Category", b =>
                {
                    b.Navigation("SportingGoods");
                });

            modelBuilder.Entity("sport.Models.Manufacturer", b =>
                {
                    b.Navigation("SportingGoods");
                });

            modelBuilder.Entity("sport.Models.Order", b =>
                {
                    b.Navigation("OrdersSportingGoods");
                });

            modelBuilder.Entity("sport.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("sport.Models.SportingGood", b =>
                {
                    b.Navigation("OrdersSportingGoods");
                });

            modelBuilder.Entity("sport.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("sport.Models.Supplier", b =>
                {
                    b.Navigation("SportingGoods");
                });

            modelBuilder.Entity("sport.Models.UnitsOfMeasurement", b =>
                {
                    b.Navigation("SportingGoods");
                });

            modelBuilder.Entity("sport.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
